// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web1Shamil.Data;

namespace Web1Shamil.Migrations
{
    [DbContext(typeof(MContext))]
    partial class MContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Web1Shamil.Models.Classes.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoachName");

                    b.Property<string>("CoachSurname");

                    b.HasKey("CoachId");

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("Web1Shamil.Models.Classes.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.Property<int?>("TeamsId");

                    b.HasKey("Id");

                    b.HasIndex("TeamsId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Web1Shamil.Models.Classes.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CoachId");

                    b.Property<string>("Name");

                    b.Property<string>("Stadium");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Web1Shamil.Models.Classes.Players", b =>
                {
                    b.HasOne("Web1Shamil.Models.Classes.Teams", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamsId");
                });

            modelBuilder.Entity("Web1Shamil.Models.Classes.Teams", b =>
                {
                    b.HasOne("Web1Shamil.Models.Classes.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");
                });
#pragma warning restore 612, 618
        }
    }
}
